# Generated by Django 2.2 on 2020-04-09 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', multiselectfield.db.fields.MultiSelectField(choices=[('Anxiety', 'Anxiety'), ('Arthritis', 'Arthritis'), ('Asthma', 'Asthma'), ('Anemia', 'Anemia'), ('Cancer', 'Cancer'), ('Corona_virus', 'Corona_virus'), ('Diabetes', 'Diabetes'), ('Ebola', 'Ebola'), ('HIV', 'HIV')], max_length=50)),
                ('symptoms', models.CharField(max_length=100)),
                ('additional_info', models.CharField(max_length=100)),
                ('disability', models.BooleanField(default=False)),
                ('medications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
