# Generated by Django 2.2 on 2020-05-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='illness',
            field=models.CharField(choices=[('Anxiety', 'Anxiety'), ('Arthritis', 'Arthritis'), ('Asthma', 'Asthma'), ('Anemia', 'Anemia'), ('Cancer', 'Cancer'), ('Corona_virus', 'Corona Virus'), ('Diabetes', 'Diabetes'), ('Ebola', 'Ebola'), ('HIV', 'HIV')], max_length=50),
        ),
    ]
